site_name: ELTE IK's Specificator documentation

nav: 
    - Home: index.md
    - 'How to write a specification': how-to-write-a-specification.md
    - 'How to input data': how-to-input-data.md

theme:
    name: null                  # Disable Material theme
    custom_dir: terminal_theme/ # Use your custom HTML template
    
extra_css:                      # <--- THIS IS KEY FOR PATH RESOLUTION
  - overrides/css/main.css      # MkDocs will correctly link this on all pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg