site_name: ELTE IK's Specificator

site_url: https://unnobatroo.github.io/elte-specificator-en/
repo_url: https://github.com/unnobatroo/elte-specificator-en

nav: 
    - Home: index.md
    - 'How to write a specification': how-to-write-a-specification.md
    - 'How to input data': how-to-input-data.md
    - "POA's cheatsheet": poas-cheatsheet.md

theme:
    name: 'readthedocs'

extra_css:
  - overrides/css/main.css

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - overrides/js/footer-injector.js