site_name: ELTE IK's Specificator documentation

nav: 
    - Home: index.md
    - 'How to write a specification': how-to-write-a-specification.md
    - 'How to input data': how-to-input-data.md

theme:
    name: 'material'
    custom_dir: overrides/  # <-- DIRECTS MKDOCS TO USE YOUR OVERRIDE FOLDER
    palette:
      scheme: slate       # Dark base
      primary: black      # Set the primary color to black
      accent: lime        # Set the accent color to neon green
      
    features:
        - navigation.top
        - navigation.prev_next
        - navigation.prune
        
    extra_css:            # <-- LOADS YOUR CUSTOM STYLES
      - css/main.css
        
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg