site_name: ELTE IK's Specificator documentation

site_url: https://unnobatroo.github.io/elte-specificator-en/
# Assuming your repository is named elte-specificator-en
repo_url: https://github.com/unnobatroo/elte-specificator-en

nav: 
    - Home: index.md
    - 'How to write a specification': how-to-write-a-specification.md
    - 'How to input data': how-to-input-data.md

theme:
    name: 'material'       # <-- Use Material Theme
    palette:
      scheme: slate        # <-- Dark/Black background
      primary: black       # <-- Primary elements (header) are black
      accent: grey         # <-- Accent color (links, highlights) is subtle grey
      
    features:
        - navigation.top
        - navigation.prev_next
        - navigation.prune
        
# --- KEY CHANGE: Add your custom CSS here for ALL PAGES ---
extra_css:
  - overrides/css/main.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg